# Because of Snyk personnal account, only test weekly and not on commit.

name: Snyk Container

on:
  schedule:
    - cron: '25 15 */7 * *'
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: damballa/locust:latest-alpine

